### PR TITLE
fix: remove numpy deprecations

### PR DESCRIPTION
**Pull request by dsgibbons**
Fixes deprecation warnings as per https://github.com/slundberg/shap/pull/1890

### CODE REVIEW

**Review by thatlittleboy — COMMENTED** [review]
LGTM in general.

But there seems to be a couple more (in the notebooks) that the original PR missed. Shall we fix these too?

image

Secondly, I noticed that `np.bool8` is also getting [deprecated in numpy 1.24](https://numpy.org/doc/stable/release/1.24.0-notes.html#np-str0-and-similar-are-now-deprecated), I thought we might take this chance to also fix it here if it's not too troublesome.

image

**Comment by thatlittleboy** [comment]
There's `np.object` also that was missed out (found this while running tests)

```python
>>> import numpy as np; np.__version__
'1.24.3'
>>> np.object
<stdin>:1: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/forks/shap/venv/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by dsgibbons** [comment]
Good spot! I think that's all of them

**Review by thatlittleboy — APPROVED** [review]
Thanks!

smiling-cat-face-lgtm

**Comment by thatlittleboy** [comment]
Just wanted to mention / link a couple more related issues about the same topic:

- slundberg#2837
- slundberg#2878
- slundberg#2911

**Pull request merged**
