### PR TITLE
Cache pip dependencies on CI

### PR DESCRIPTION
**Pull request by connortann**
Supports #42.

Adds caching of pip dependencies for faster CI times. Reduces time to install dependencies from ~4min30 to ~3mins. See [discussion on #42](https://github.com/dsgibbons/shap/issues/42#issuecomment-1571735472) for measured timings for alternative ideas, and discussion of total cache limits.

### CODE REVIEW

**Review by thatlittleboy — COMMENTED** [review]
Very nice PR @connortann ! I think it's pretty much ready for merge, but I'll throw out a thought first and let me know what you think.

 Since we are restricted by the 10Gb limit, have you tried caching only the dependencies that require building? (is it pyspark or pytorch..?) Since wheel installations are pretty fast, it may be more optimal to cache, say, pyspark for all 5 python versions than caching everything for 3 versions.

I think the cache action takes a list of directories/paths, maybe we could identify the slowest packages and just cache those?

**Comment by connortann** [comment]
Fantastic idea @thatlittleboy , I'll take a look and have a go! It would certainly be neater to have the same approach for all environments.

**Comment by connortann** [comment]
To decide which packages to cache: we want to save the most time, whilst keeping under ~2GB total cache size per env.

Some calculations from experimentation:

| Package                          | size (MB) | built time (s) | s / MB |
|------------------------------|--------|-----|----------|
|site-packages/pyspark*      |  310   |  12s  |   0.039  |
|site-packages/nvidia*         |  1521 |   40s  |   0.026  |
|site-packages/torch*          |  619   |   13s  |   0.021  |
|site-packages/tensorflow* |    586 |   12s  |   0.020  |
|site-packages/xgboost*     |    200 |   4s    |  0.020   |

**Review by thatlittleboy — APPROVED** [review]
Nice one. Let's run this for a bit and see how it goes. Merging..

walkby-cat-high-five-shipit

**Pull request merged**
